-  job:
    name: install-cnf-cert-ts-reqs
    roles:
      - ensure-go:
      - ensure-golangci-lint:

- project:
    check:
      jobs:
        - install-cnf-cert-ts-reqs:

    gate:
      jobs:
        - install-cnf-cert-ts-reqs: